### ISSUE TITLE
Edit option for existing player is not working.

### ISSUE THREAD

**Issue by Cricplatoon** [parvezmrobin/jhijhi#1]
**Browser :** Google Chrome.
**Steps to reproduce :**
1. Go to Player section.
2. Create a player if there is no existing player.
3. Now in 'Existing Players' section, click on Edit button.

![image](https://user-images.githubusercontent.com/20716800/57980001-e59bc080-7a46-11e9-990d-c1e01d186a53.png)

**Observed:** Nothing happened after clicking on Edit button.
**Expected Result:** User should be abled to edit a player information.

**Comment by parvezmrobin** [comment]
Actually, it wasn't implemented and I forgot to hide the edit button. 🤦‍♂ 🤦‍♂ 🤦‍♂ 
Anyway, it's implemented now. Will you please check it again and close the issue if fixed?

**Comment by Cricplatoon** [comment]
User can edit now. But user needs to click two times in Edit button to edit player infomation. There is another observation. If you click Edit button of player 1, nothing will happen. Then if you click Edit button of player 2, 'Edit Player' of player 1 will be activated. Edit Player section of a player should be enabled for the first click in Edit button of that player.

**Comment by parvezmrobin** [comment]
Hopefully fixed. Will you please recheck?

**Comment by Cricplatoon** [comment]
**Fix is working properly.** Edit option for existing player is now working.
