### ISSUE TITLE
Jersey number should be in fixed range.

### ISSUE THREAD

**Issue by Cricplatoon** [parvezmrobin/jhijhi#2]
**Suggestion :** Currently user can set unlimited digits in 'Jersey No' text field. We should fixed a range for jersey no. User will be allowed to use 2-3 digits no. Range should be 0 to 999.

![image](https://user-images.githubusercontent.com/20716800/57981229-feac6d80-7a56-11e9-9072-d7efd6956747.png)

![image](https://user-images.githubusercontent.com/20716800/57981392-a5ddd480-7a58-11e9-97f7-55a3ad185570.png)
**0** will be a jersey no.

**Comment by parvezmrobin** [comment]
Hopefully fixed. However, exactly after pushing the fix I had a second thought. This app is intended to be flexible enough and disallow most of the restrictions that an actual cricket match impose. Like No number of overs or number of players rule. Now, if someone wants his jersey to be number 345457834347, why would I mind?

**Comment by Cricplatoon** [comment]
**Leading 0** should not appear in jersey no.

![image](https://user-images.githubusercontent.com/20716800/57984177-0847cc80-7a7b-11e9-8d3b-4ed35408fb71.png)

For making a great app, you have to think about all possible scenarios and should restrict users from unusual behavior.

**Comment by parvezmrobin** [comment]
Although `jerseyNo` 00240 is stored as 240 in the server, this validation is now also implemented the UI. Additionally, from now, 0 is also a valid `jerseyNo`.

**Comment by Cricplatoon** [comment]
**Suggestion has been implemented properly.**
