### ISSUE TITLE
First letters of a person's first, middle and last names will be uppercase.

### ISSUE THREAD

**Issue by Cricplatoon** [parvezmrobin/jhijhi#3]
**Bug 1 :** From capitalization rules, the first letters of a person's first, middle and last names will be uppercase. Currently we only keep first letter of first name in uppercase and first letters of middle and last names are still in lowercase. We should follow the capitalization rules.

![image](https://user-images.githubusercontent.com/20716800/57984505-35e24500-7a7e-11e9-8d40-c1feebb8905c.png)

**Bug 2 :** User can entry same player name by giving extra space ' ' before or after or any where in a name. We should omit those leading or following spaces when saving. We should also keep single space between two parts of a name even if user put multiple spaces.

![image](https://user-images.githubusercontent.com/20716800/57984660-d6853480-7a7f-11e9-935e-c4aa34a9f8fa.png)

**Comment by parvezmrobin** [comment]
Fixed.

Sent from Mail for Windows 10

From: Fahim Rahman
Sent: Sunday, May 19, 2019 10:03 PM
To: parvezmrobin/jhijhi
Cc: Subscribed
Subject: [parvezmrobin/jhijhi] First letters of a person's first, middle andlast names will be uppercase. (#3)

Bug 1 : From capitalization rules, the first letters of a person's first, middle and last names will be uppercase. Currently we only keep first letter of first name in uppercase and first letters of middle and last names are still in lowercase. We should follow the capitalization rules.

Bug 2 : User can entry same player name by giving extra space ' ' before or after or any where in a name. We should omit those leading or following spaces when saving. We should also keep single space between two parts of a name even if user put multiple spaces.

**Comment by parvezmrobin** [comment]
Hopefully fixed.

**Comment by Cricplatoon** [comment]
**Fix for Bug 1 and Bug 2 are now working properly.**
