### ISSUE TITLE
Navbar dropdown doesn't close after routing

### ISSUE THREAD

**Issue by Alamin02** [parvezmrobin/jhijhi#4]
After selecting a menu item, it's normally expected to close, but its not closing. 

![change password click](https://user-images.githubusercontent.com/13636502/67358816-552c5380-f583-11e9-9943-e741ff5ef48c.PNG)

![manage account click](https://user-images.githubusercontent.com/13636502/67358817-55c4ea00-f583-11e9-8466-8dc58b1e9306.PNG)

These are the state after routing.

**Comment by parvezmrobin** [comment]
It's fixed but the fix created another issue that the navbar sometimes crashes. Hence, I may revert the fix in the future.
