### ISSUE TITLE
Empty  dropdown selector should have a placeholder

### ISSUE THREAD

**Issue by Alamin02** [parvezmrobin/jhijhi#5]
**Suggestion:** Selector dropdowns are empty when no players are selected. It should have a placeholder with instruction to select players first for a better UX.

![Captain](https://user-images.githubusercontent.com/13636502/67359444-0aabd680-f585-11e9-98bc-fa4072dc2a81.PNG)

**Comment by parvezmrobin** [comment]
I have updated the UI and you are welcomed to recheck.

**Comment by Alamin02** [comment]
It's fixed it a way but I think better phrasing would be - "Choose players first to select captain"

**Comment by parvezmrobin** [comment]
It's updated now.
