### ISSUE TITLE
Register function not working

### ISSUE THREAD

**Issue by Alamin02** [parvezmrobin/jhijhi#6]
**Bug:** When register button is clicked after the form filled up, nothing happens. Consoles shows error.

![Register](https://user-images.githubusercontent.com/13636502/67374026-718bb880-f5a2-11e9-9679-5d5c7b93a1a8.PNG)

**Comment by parvezmrobin** [comment]
There was an issue with Axios's cancelation token. Hopefully, it's fixed.

**Comment by Alamin02** [comment]
Negative.  It just started failing differently! Check the screenshot. not sure if this is the desired output. At lease the error message should be clear about why it failed.

![Jhi jhi 2](https://user-images.githubusercontent.com/13636502/67491463-d50cf900-f629-11e9-98fc-42250af134c6.PNG)

**Comment by parvezmrobin** [comment]
Hopefully, it's fixed now. Can you please recheck?

**Comment by Alamin02** [comment]
Yep, now it works accordingly.
